### ISSUE TITLE
Plugin causes NullPointerException

### ISSUE THREAD

**Issue by DennisBecker** [boonwin/BoonwinsBattlegroundsTracker#16]
I have HDT v1.14.8 and latest Plugin v0.0.1.2 and get the following error with latest Heathstone patch:

```
Make sure you are using the latest version of the Plugin and HDT.

System.NullReferenceException: Object reference not set to an instance of an object.
   at BoonwinsBattlegroundTracker.BgMatchData.SetLatestRating()
   at BoonwinsBattlegroundTracker.BgMatchData.Update()
   at BoonwinsBattlegroundTracker.BgMatchDataPlugin.OnUpdate()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Update() in D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Plugins\PluginWrapper.cs:line 115
```

**Comment by DennisBecker** [comment]
This was fixed by HDT in v1.14.10-
